language: d

os:
  - linux
  - osx

d:
  - dmd
  - ldc

env:
    - TEST_DIR=docs/getopt
    - TEST_DIR=docs/string
script:
    echo $TEST_DIR &&
    cd $TEST_DIR &&
    ${DC} -unittest -main -run app.d
