version: 2
jobs:
  test-dmd:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run:
          name: test
          command: .circleci/test.sh dmd
      - persist_to_workspace:
          root: generated-docs
          paths: .
  deploy-docs:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: generated-docs
      - run:
          name: deploy
          command: .circleci/deploy.sh dmd
workflows:
  version: 2
  generate-docs:
    jobs:
      - test-dmd
      - deploy-docs:
          requires:
            - test-dmd
          filters:
            branches:
              only:
                - master
