version: 2
jobs:
  test-dmd:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - run:
          name: test
          command: bash .circleci/test.sh dmd
  deploy-docs:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - run:
          name: Update enviroment
          command: sudo apt update && sudo apt install -y rsync
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "86:2e:1c:79:04:7a:22:83:24:b9:70:6a:ab:5e:91:82	"
      - run:
          name: deploy
          command: bash .circleci/deploy.sh dmd
workflows:
  version: 2
  generate-docs:
    jobs:
      - test-dmd
      - deploy-docs:
          requires:
            - test-dmd
          filters:
            branches:
              only:
                - master
